### ISSUE TITLE
Workflow Environment Variables window?

### ISSUE THREAD

**Issue by frankmeeuwsen** [skibitsky/alfred-timing#1]
I installed the package and have an API key. But where can I find the Workflow Environment Variables window to put the API key?

**Comment by frankmeeuwsen** [comment]
nvm, I found it in Alfred prefs > Workflow > [x] button top right of the Timing Workflow. It does give your API key though. Maybe worth checking that out.

**Comment by skibitsky** [comment]
Hello @frankmeeuwsen, 
Thank you for your report. 
I will update the instructions in Readme to make it clearer :)
